import type {Problem} from '../types';
import type {InsightModel,IntuitionFrameData,RuleFocus,VisualFrame,VisualizerAdapter} from './types';

type KokoInput={piles:number[];h:number};
type SpecialInput={nums:number[]};

function parseObject(raw:string){try{return JSON.parse(raw) as Record<string,unknown>}catch{throw new Error('Use the JSON shape shown in the example.')}}
function numericArray(value:unknown,label:string){if(!Array.isArray(value)||!value.length||!value.every(item=>Number.isFinite(Number(item))))throw new Error(`${label} must be a non-empty numeric array.`);if(value.length>20)throw new Error('Use at most 20 values for a readable trace.');return value.map(Number)}

function rules(active:string):RuleFocus[]{return [{token:'low…high',meaning:'possible answers',active:active==='range'},{token:'mid',meaning:'candidate, not array index',active:active==='mid'},{token:'feasible(mid)',meaning:'monotonic yes/no test',active:active==='test'},{token:'bounds',meaning:'discard an impossible half',active:active==='bounds'},{token:'answer',meaning:'verify the boundary',active:active==='answer'}]}

function frame(phase:string,title:string,message:string,insights:InsightModel,view:IntuitionFrameData['binarySearch'],active:string):VisualFrame{return {phase,title,message,kind:'intuition',data:{variant:'binary-search',insights,rules:rules(active),binarySearch:view} satisfies IntuitionFrameData}}

const kokoInsights:InsightModel={state:'low…high contains every eating speed that could still be the minimum valid answer.',base:'Speed 1 is the smallest possible; max(piles) is always fast enough when h ≥ number of piles.',choice:'Test one candidate speed by totaling ceil(pile / speed) hours.',invariant:'Feasibility is monotonic: once a speed works, every faster speed also works.'};

function parseKoko(raw:string):KokoInput{const value=parseObject(raw);const piles=numericArray(value.piles,'piles');const h=Number(value.h);if(!Number.isInteger(h)||h<piles.length)throw new Error('h must be an integer at least as large as the number of piles.');return {piles,h}}
function kokoFrames(value:unknown,_problem:Problem):VisualFrame[]{const {piles,h}=value as KokoInput;let low=1;let high=Math.max(...piles);const frames:VisualFrame[]=[frame('BASE','Search speeds, not pile positions','The answer may be any integer speed from 1 through the largest pile.',kokoInsights,{values:piles,low,high,mid:null,metricLabel:'TOTAL HOURS',metric:null,verdict:'not tested',answer:null,context:`piles [${piles.join(', ')}] · h = ${h}`},'range')];while(low<high){const mid=Math.floor((low+high)/2);const hours=piles.reduce((total,pile)=>total+Math.ceil(pile/mid),0);const feasible=hours<=h;frames.push(frame('TEST',`Try speed ${mid}`,feasible?`${hours} hours fits the deadline. Keep this speed and everything faster; look left for a smaller valid speed.`:`${hours} hours misses the deadline. Every slower speed also fails, so move right.`,kokoInsights,{values:piles,low,high,mid,metricLabel:'TOTAL HOURS',metric:hours,verdict:feasible?'feasible → high = mid':'too slow → low = mid + 1',answer:null,context:`Σ ceil(pile / ${mid}) · deadline ${h}`},'test'));if(feasible)high=mid;else low=mid+1}frames.push(frame('COMPLETE','First feasible speed found',`The search interval collapsed to ${low}.`,kokoInsights,{values:piles,low,high,mid:low,metricLabel:'TOTAL HOURS',metric:piles.reduce((total,pile)=>total+Math.ceil(pile/low),0),verdict:'first true',answer:low,context:`minimum valid speed for h = ${h}`},'answer'));return frames}

const specialInsights:InsightModel={state:'The candidate x is an answer value between 0 and n; it does not need to appear in nums.',base:'x = 0 and x = n bound every possible count of qualifying elements.',choice:'For a candidate x, count how many values are at least x.',invariant:'count(nums ≥ x) ≥ x changes monotonically from true to false as x grows.'};

function parseSpecial(raw:string):SpecialInput{const value=parseObject(raw);const nums=numericArray(value.nums,'nums');if(nums.some(item=>!Number.isInteger(item)||item<0))throw new Error('nums must contain non-negative integers.');return {nums}}
function specialFrames(value:unknown,_problem:Problem):VisualFrame[]{const {nums}=value as SpecialInput;let low=0;let high=nums.length;const frames:VisualFrame[]=[frame('BASE','Search the answer value x','Array indices and array values are irrelevant to the search space: x can only be 0…n.',specialInsights,{values:nums,low,high,mid:null,metricLabel:'COUNT ≥ x',metric:null,verdict:'not tested',answer:null,context:`nums [${nums.join(', ')}] · n = ${nums.length}`},'range')];let answer=-1;while(low<=high){const mid=Math.floor((low+high)/2);const count=nums.filter(number=>number>=mid).length;const verdict=count===mid?'exact equality → return x':count>mid?'too many → move left = mid + 1':'too few → move right = mid − 1';frames.push(frame(count===mid?'COMPLETE':'TEST',`Try x = ${mid}`,count===mid?`${count} values are at least x, so the reference returns ${mid}.`:count>mid?`${count} values qualify, so the answer must be larger than ${mid}.`:`Only ${count} values qualify, so ${mid} and larger candidates are impossible.`,specialInsights,{values:nums,low,high,mid,metricLabel:'COUNT ≥ x',metric:count,verdict,answer:count===mid?mid:null,context:`count(nums ≥ ${mid}) = ${count}`},count===mid?'answer':'test'));if(count===mid){answer=mid;break}if(count>mid)low=mid+1;else high=mid-1}if(answer<0)frames.push(frame('COMPLETE','No exact x exists','The search exhausted every candidate without count(nums ≥ x) equaling x.',specialInsights,{values:nums,low,high,mid:null,metricLabel:'COUNT ≥ x',metric:nums.filter(number=>number>=Math.max(0,low)).length,verdict:'return -1',answer:-1,context:'final equality was never found'},'answer'));return frames}

export const kokoVisualizer:VisualizerAdapter={id:'koko-eating-bananas',name:'Binary search on the answer',mode:'specialized',description:'Watch the candidate speed interval shrink around the first feasible value.',inputLabel:'FEASIBILITY PARAMETERS · piles, h',placeholder:'{"piles":[3,6,7,11],"h":8}',presets:[{label:'Default example',input:'{"piles":[3,6,7,11],"h":8}',source:'LeetCode'},{label:'Tight deadline',input:'{"piles":[30,11,23,4,20],"h":5}',source:'LeetCode'},{label:'One extra hour',input:'{"piles":[30,11,23,4,20],"h":6}',source:'LeetCode'},{label:'Single pile',input:'{"piles":[9],"h":3}',source:'Diagnostic'}],parseInput:parseKoko,createFrames:kokoFrames};

export const specialArrayVisualizer:VisualizerAdapter={id:'special-array-with-x-elements-greater-than-or-equal-x',name:'Binary search a candidate value',mode:'specialized',description:'Separate the candidate answer x from array indices and verify the monotonic boundary.',inputLabel:'COUNTING PARAMETERS · nums',placeholder:'{"nums":[3,5]}',presets:[{label:'Answer does not appear',input:'{"nums":[3,5]}',source:'LeetCode'},{label:'No valid x',input:'{"nums":[0,0]}',source:'LeetCode'},{label:'Mixed zeros',input:'{"nums":[0,4,3,0,4]}',source:'LeetCode'},{label:'Boundary not exact',input:'{"nums":[3,6,7,7,0]}',source:'Diagnostic'}],parseInput:parseSpecial,createFrames:specialFrames};
