import type {Problem} from '../types';
import type {InsightModel,IntuitionFrameData,RuleFocus,SubsetPruningView,VisualFrame,VisualizerAdapter} from './types';

type SubsetInput={nums:number[]};
const insights:InsightModel={state:'The path is one chosen subset; start is the first index the next choice may use.',base:'Every path is already a valid subset. When start reaches n, the candidate loop is empty and returns naturally.',choice:'Choose one candidate, recurse with the next index, then remove it to try its siblings.',invariant:'Indices always increase, so each multiset choice has one construction order.'};
function rules(active:string):RuleFocus[]{return [{token:'record(path)',meaning:'every node is an answer',active:active==='record'},{token:'j starts at start',meaning:'indices only move forward',active:active==='choose'},{token:'j > start',meaning:'not the first sibling',active:active==='skip'},{token:'nums[j]==nums[j-1]',meaning:'duplicate sibling',active:active==='skip'},{token:'pop',meaning:'restore this recursion level',active:active==='remove'}]}
function parseInput(raw:string):SubsetInput{let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error('Use {"nums":[1,2,2]}.')}const nums=Array.isArray(value)?value:(value as {nums?:unknown})?.nums;if(!Array.isArray(nums)||!nums.every(item=>Number.isFinite(Number(item))))throw new Error('nums must be a numeric array.');if(nums.length>8)throw new Error('Use at most 8 values for a readable recursion trace.');return {nums:nums.map(Number)}}
function frame(phase:string,title:string,message:string,view:SubsetPruningView,active:string):VisualFrame{return {phase,title,message,kind:'intuition',data:{variant:'subset-pruning',insights,rules:rules(active),subsetPruning:{...view,values:[...view.values],path:[...view.path],candidates:view.candidates.map(candidate=>({...candidate}))}} satisfies IntuitionFrameData}}
function createFrames(value:unknown,_problem:Problem):VisualFrame[]{const nums=[...(value as SubsetInput).nums].sort((a,b)=>a-b);const path:number[]=[];let resultCount=0;const frames:VisualFrame[]=[];const candidates=(start:number,current:number|null,skipped:number|null):SubsetPruningView['candidates']=>nums.slice(start).map((number,offset)=>{const index=start+offset;const state:SubsetPruningView['candidates'][number]['state']=index===current?'chosen':index===skipped?'skipped':'available';return {index,value:number,state}});
  const visit=(start:number)=>{resultCount+=1;frames.push(frame('SOLUTION',path.length?`Record [${path.join(', ')}]`:'Record the empty subset','The current path is valid before choosing anything else.',{values:nums,path,level:path.length,candidates:candidates(start,null,null),resultCount},'record'));for(let j=start;j<nums.length;j+=1){if(j>start&&nums[j]===nums[j-1]){frames.push(frame('PRUNE',`Skip duplicate sibling ${nums[j]} at index ${j}`,`Index ${j-1} already started an identical branch at this same recursion level.`,{values:nums,path,level:path.length,candidates:candidates(start,null,j),resultCount},'skip'));continue}path.push(nums[j]);frames.push(frame('CHOICE',`Choose ${nums[j]} at index ${j}`,`Move deeper with start = ${j+1}. A later equal copy is allowed there because it is no longer a sibling choice.`,{values:nums,path,level:path.length,candidates:candidates(start,j,null),resultCount},'choose'));visit(j+1);const removed=path.pop()!;frames.push(frame('BACKTRACK',`Remove ${removed}`,'Restore the parent path so the next sibling starts from the same state.',{values:nums,path,level:path.length,candidates:candidates(start,null,null),resultCount},'remove'));}};
  frames.push(frame('RECOGNIZE','Sort to place equal siblings together','The skip rule compares adjacent candidates only after sorting.',{values:nums,path,level:0,candidates:candidates(0,null,null),resultCount},'skip'));visit(0);frames.push(frame('COMPLETE','All unique subsets generated',`${resultCount} unique subsets were recorded without generating duplicate branches.`,{values:nums,path,level:0,candidates:[],resultCount},'record'));return frames}
export const subsetsVisualizer:VisualizerAdapter={id:'subsets-ii',name:'Recursion level + sibling pruning',mode:'specialized',description:'See why equal siblings are skipped while an equal value remains legal one recursion level deeper.',inputLabel:'BACKTRACKING PARAMETER · nums',placeholder:'{"nums":[1,2,2]}',presets:[{label:'Default duplicate pair',input:'{"nums":[1,2,2]}',source:'LeetCode'},{label:'All duplicates',input:'{"nums":[2,2,2]}',source:'Diagnostic'},{label:'No duplicates',input:'{"nums":[1,2,3]}',source:'Diagnostic'},{label:'Duplicate groups',input:'{"nums":[1,1,2,2]}',source:'Diagnostic'},{label:'Empty input',input:'{"nums":[]}',source:'Diagnostic'}],parseInput,createFrames};
