import {useQuery} from '@tanstack/react-query';
import {Activity,Atom,BookOpen,GitBranch,Hexagon,Plus,Settings2} from 'lucide-react';
import {useState} from 'react';
import {NavLink,Outlet,useNavigate} from 'react-router-dom';
import {api} from '../api';
import type {Analytics} from '../types';
import {CommandPalette} from './CommandPalette';
const nav=[[Atom,'Atlas','/'],[Activity,'Dashboard','/dashboard'],[BookOpen,'Library','/library'],[Hexagon,'Taxonomy','/taxonomy'],[GitBranch,'Sync','/settings'],[Settings2,'Settings','/settings']] as const;
export function AppLayout(){const navigate=useNavigate();const[commandOpen,setCommandOpen]=useState(false);const{data}=useQuery({queryKey:['analytics'],queryFn:()=>api<Analytics>('/api/analytics/overview')});return <div className="app-shell"><aside className="sidebar"><NavLink className="brand-mark" to="/" aria-label="Algo Atlas home"><Atom size={23}/><i/></NavLink><nav>{nav.map(([Icon,label,path],index)=><NavLink end={path==='/'} to={path} key={`${label}-${index}`} aria-label={label} className={({isActive})=>isActive?'active':''}><Icon size={19}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-status"><span/><small>LOCAL</small></div></aside><main className="main-shell"><header className="topbar"><NavLink to="/" className="wordmark"><p className="eyebrow">PERSONAL KNOWLEDGE SYSTEM</p><h1>ALGO <b>ATLAS</b></h1></NavLink><button className="search" onClick={()=>setCommandOpen(true)}><span className="search-icon">⌕</span><span>Search your problem universe</span><kbd>⌘ K</kbd></button><div className="top-actions"><button className="sync-pill" onClick={()=>navigate('/settings')}><i/> {data?.summary.unsynced_files??0} UNSYNCED</button><button className="add" onClick={()=>navigate('/problems/new')}><Plus size={18}/> LOG MISTAKE</button></div></header><Outlet/></main><nav className="mobile-nav">{nav.slice(0,5).map(([Icon,label,path])=><NavLink end={path==='/'} to={path} key={label} aria-label={label}><Icon size={20}/></NavLink>)}</nav><CommandPalette open={commandOpen} onOpenChange={setCommandOpen}/></div>}
